config/routes.rb
Rails.application.routes.draw do



  get 'comments/create'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "colleges#index"

  resources :colleges

  get '/posts/:college' => 'posts#index' , as:'posts'
  post '/posts/:college' => 'posts#create'
  delete '/posts/:id' => 'posts#destroy' , as:'post'
  # resources :posts, only: [:create] 4

  get '/user/:id' => 'users#profile' , as: 'user_profile'

  resources :comments
  resources :likes , only: [:create]
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :likes , as: :parent
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :parent , polymorphic: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes , as: :parent
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

	def index
		@collegeNew = College.new
		@college = College.all
	end

	def create
		@college = College.create(
				collegename: params[:college][:collegename],
			)
		redirect_to action: 'index'
	end

	def destroy
		@college = College.find(params[:id])
		@college.destroy
		redirect_to action: 'index'
	end

	


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
  	if params[:mode] == '0'
  		@comment = Comment.create(
  				content: params[:content],
  				user_id: current_user.id,
  				post_id: params[:post_id],
  			)
  	else @comment = Comment.create(
  				content: params[:content],
  				user_id: '2',
  				post_id: params[:post_id],
  			)
  	end

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		
		likeExist = Like.exists?(user: current_user , parent_id: params[:parent_id] , parent_type: params[:parent_type])  
		
		if(!likeExist)
			@like = Like.create(
					user_id: current_user.id,
					parent_id: params[:parent_id],
					parent_type: params[:parent_type],
				)
		else
			@like = Like.where(user_id: current_user.id , parent_id: params[:parent_id] , parent_type: params[:parent_type])[0]
			@like.destroy

		end

		# redirect_to posts_path , college: params[:college]
	end





end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  	def index

  		if !College.exists?(collegename: params[:college])
  			redirect_to root_path
  		end

		@postNew = Post.new
		@post = Post.where(college: params[:college])
		# @comment = Comment.new		

	end

	def create
			
			if params[:mode] == '0'
				@p = Post.create(
					content: params[:content],
					user_id: current_user.id ,
					college: params[:college]
					)
			else @p = Post.create(
					content: params[:content],
					user_id: "2" ,
					college: params[:college]
					)
			end
			redirect_to action: 'index'  
	end

	def destroy
		
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to action: "index", college: @post.college

	end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile

  	@post = Post.where(user_id: params[:id])
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/colleges/index.html.erb
<p>College Index</p>

<div>
	<%=form_for @collegeNew do |collegeNew|%>
		<%=collegeNew.label :collegename%>
		<%=collegeNew.text_field :collegename%>
		<%=collegeNew.submit 'Create College'%>
	<%end%>
</div>

<div>
	<% @college.each do |college|%>
		<p>
			<%= link_to college.collegename , posts_path(college.collegename)%>
			<%= link_to "Delete" , college_path(college)  , method: :delete , confirm: "Are you sure?"%>
		</p>
		
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raazkholo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<header id="body-header">
			<ul>
				<% if user_signed_in? %>
					<li>
						<p><%= current_user.email %></p>
					</li>
					<li>
						<%= link_to "Home", root_path  %>
					</li>
					<li>
						<p><%= link_to "My post", user_profile_path(current_user.id) %></p>
					</li>
					<li>
						<p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
					</li>
				<% else %>
					<li>
						<p><%= link_to "Sign In", new_user_session_path %></p>
					</li>
					<li>
						<p><%= link_to "Sign Up", new_user_registration_path %></p>
					</li>
				<% end %>
			</ul>
	</header>

  	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
	<%=post.content%>
	<small><sub><%=post.user.email%></sub></small>

	<%= form_with url: likes_path do |form|%>
		<%= form.hidden_field :parent_id, value: post.id %>
		<%= form.hidden_field :parent_type, value: 'Post' %>

		<%if Like.exists?(user_id: current_user.id , parent_type: 'Post' , parent_id: post.id)%>
			<%=form.submit'Liked'%>
		<%else%>
			<%=form.submit'Like'%>
		<%end%>

	<%end%>

	<%=post.likes.length%>



	<%= link_to "Delete", post_path(post) , method: :delete%>

	<%= form_with url: comments_path do |form|%>
		<%= form.label :comment%>
		<%= form.text_field :content%>
		<%= form.label "Secret Mode" %> 
    	<%= form.check_box :mode %>
    	<%= form.hidden_field :post_id, value: post.id %>
    	<%= form.submit'create comment'%>
    <%end%>

    <ul>
    <%post.comments.each do |comment|%>
   		<li>
    		<%=comment.content%>
			<small><sub><%=comment.user.email%></sub></small>
			<%= form_with url: likes_path do |form|%>
				<%= form.hidden_field :parent_id, value: comment.id %>
				<%= form.hidden_field :parent_type, value: 'Comment' %>

				<%if Like.exists?(user_id: current_user.id , parent_type: 'Comment' , parent_id: comment.id)%>
					<%=form.submit'Liked'%>
				<%else%>
					<%=form.submit'Like'%>
				<%end%>


			<%end%>
			<%=comment.likes.length%>
		</li>
	<%end%>
	</ul>



</li>

app/views/posts/index.html.erb
<h1><%=params[:college]%> Posts</h1>
<div>
	<%=form_with url: posts_path do |postNew|%>

		<%=postNew.label :content%>
		<%=postNew.text_field :content%>

		<%= postNew.label "Secret Mode" %> 
    	<%= postNew.check_box :mode %> 


		<%=postNew.submit 'Create Post'%>

	<%end%>
</div>
<div>
	<% @post.each do |post|%>
		<ul>
			<%= render "post", post: post %>
		</ul>
		
	<%end%>
</div>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
	<% @post.each do |post|%>
	<%= render "posts/post", post: post %>
<%end%>